// shortly/src/routes/login/login.svelte
<script>
	import imgLogo from '$lib/images/logo.svg';
	import { account, auth } from '$lib/store';
	import { goto } from '$app/navigation';
	import { base } from '$app/paths';

	let username = '';
	let password = '';
	let error = false;

	const handleSubmit = (event) => {
		event.preventDefault();
		if (!username.match(/^[a-zA-Z0-9]+$/)) {
			error = true;
			return;
		}

		$account = username;
		goto(`${base}/`);
	};
	const handleClick = (value) => {
		$auth = value;
	};
</script>

<section class="mb-12 text-center">
	<a href="{base}/">
		<img src={imgLogo} alt="Shortly" class="mx-auto" />
	</a>
	<h1>User Login</h1>
</section>

<div class="mb-4">
	<form on:submit={handleSubmit} method="POST" action="/" class="flex flex-col gap-2">
		<input
			bind:value={username}
			type="text"
			name="email"
			placeholder="username"
			class="rounded-xl border-2 border-clr-Gray px-6 py-4"
			class:border-red-500={error}
			required
		/>
		<span class="mb-1 text-base text-red-500" class:hidden={!error}
			>Username can only contain letters and numbers</span
		>
		<input
			bind:value={password}
			type="password"
			name="password"
			placeholder="password"
			class="rounded-xl border-2 border-clr-Gray px-6 py-4"
			required
		/>
		<!-- create checkbox -->
		<div class="mb-1 flex justify-between">
			<label for="remember" class="flex items-center gap-x-1.5">
				<input type="checkbox" name="remember" id="remember" />
				Remember me
			</label>
			<a
				href="{base}/login"
				class="text-blue-500"
				handleClickSignup
				on:click={() => handleClick('forgot')}>Forgot Password?</a
			>
		</div>
		<button type="submit" class="rounded-xl bg-clr-Cyan py-4 font-PoppinsBold text-white"
			>Login</button
		>
	</form>
</div>
<span>
	Don't have an account?
	<button type="button" class="text-blue-500" on:click={() => handleClick('signup')}>
		Sign Up here</button
	>
</span>

// ecommerce/src/routes/login/Login.tsx
import { useState } from 'react';
import Picture from '@ui/components/Picture';
import { Google } from '@ui/assets/Icons';

export default function Page() {
  const [mode, setmode] = useState('login');

  return (
    <div className="mx-auto grid max-w-screen-2xl grid-cols-[auto_1fr] justify-between py-16">
      <Picture src="/login/side_image.png" alt="login" />
      {mode === 'login' && (
        <div className="grid items-center">
          <section className="mx-auto w-full max-w-[370px]">
            <h1 className="mb-6 font-heading-medium text-36">Login to Exlusive</h1>
            <p className="mb-2">Enter your details below</p>
            <form action="/api/login" method="post" className="grid gap-y-10 py-10">
              <input
                type="email"
                name="email"
                placeholder="Email Adress"
                className="border-b border-black px-2 pb-2"
              />
              <input
                type="password"
                name="password"
                placeholder="Password"
                className="border-b border-black px-2 pb-2"
              />
              <div className="grid grid-rows-[repeat(2,3.5rem)] gap-y-4">
                <button type="submit" className="rounded bg-clr-ButtonRed font-medium text-white">
                  Login
                </button>
                <a
                  href="/"
                  className="flex items-center justify-center gap-x-4 rounded border border-[#999999]"
                >
                  <Google />
                  Login with Google Account
                </a>
              </div>
              <div className="flex flex-col items-start gap-y-4">
                <span>
                  Don't have an account?
                  <button
                    type="button"
                    onClick={() => setmode('signup')}
                    className="ms-1 text-clr-Secondary2"
                  >
                    Sign up
                  </button>
                </span>
                <button
                  type="button"
                  onClick={() => setmode('forgot')}
                  className="text-clr-Secondary2"
                >
                  Forgot Password
                </button>
              </div>
            </form>
          </section>
        </div>
      )}
      {mode === 'signup' && (
        <div className="grid items-center">
          <section className="mx-auto w-full max-w-[370px]">
            <h1 className="mb-6 font-heading-medium text-36">Create an account</h1>
            <p className="mb-2">Enter your details below</p>
            <form action="/api/signup" method="post" className="grid gap-y-10 py-10">
              <input
                type="text"
                name="username"
                placeholder="Username"
                className="border-b border-black px-2 pb-2"
              />
              <input
                type="email"
                name="email"
                placeholder="Email Adress"
                className="border-b border-black px-2 pb-2"
              />
              <input
                type="password"
                name="password"
                placeholder="Password"
                className="border-b border-black px-2 pb-2"
              />
              <input
                type="repassword"
                name="repassword"
                placeholder="Repeat Password"
                className="border-b border-black px-2 pb-2"
              />
              <div className="grid grid-rows-[repeat(2,3.5rem)] gap-y-4">
                <button
                  type="submit"
                  className="rounded bg-clr-ButtonRed px-12 py-4 font-medium text-white"
                >
                  Create Account
                </button>
                <a
                  href="/"
                  className="flex items-center justify-center gap-x-4 rounded border border-[#999999] py-4"
                >
                  <Google />
                  Login with Google Account
                </a>
              </div>
              <span>
                Already have account?
                <button
                  type="button"
                  onClick={() => setmode('login')}
                  className="ms-1 text-clr-Secondary2"
                >
                  Login
                </button>
              </span>
            </form>
          </section>
        </div>
      )}
      {mode === 'forgot' && (
        <div className="grid items-center">
          <section className="mx-auto w-full max-w-[370px]">
            <h1 className="mb-6 font-heading-medium text-36">Forgot Password</h1>
            <p className="mb-2">Enter your Email Address</p>
            <form action="/api/forgotpassword" method="post" className="grid gap-y-10 py-6">
              <input
                type="email"
                name="email"
                placeholder="Email Adress"
                className="border-b border-black px-2 pb-2"
              />
              <button
                type="submit"
                className="rounded bg-clr-ButtonRed px-12 py-4 font-medium text-white"
              >
                Send Reset Link
              </button>
            </form>
            <button type="button" onClick={() => setmode('signup')} className="text-clr-Secondary2">
              Back to login?
            </button>
          </section>
        </div>
      )}
    </div>
  );
}
